language: python
python:
  - "3.5"
  - "3.6"
  - "3.8"
  - "nightly"
before_install:
  - pip3 install coverage
# command to install dependencies
install:
  - pip3 install -e .
# command to run tests
script:
  - coverage run --source=. -m eastereig
after_success:
  - coverage report -m
